from __future__ import annotations

import re
from pathlib import Path
from typing import Any


def _safe_text_lines(path_or_bytes: Any, scan_lines: int) -> list[str]:
    if isinstance(path_or_bytes, (str, Path)):
        p = Path(path_or_bytes)
        text = p.read_text(encoding="utf-8", errors="ignore")
    elif isinstance(path_or_bytes, (bytes, bytearray)):
        text = bytes(path_or_bytes).decode("utf-8", errors="ignore")
    else:
        text = str(path_or_bytes or "")
    lines = text.splitlines()
    return lines[: max(1, int(scan_lines))]


def validate_laser_gcode_safety(path_or_bytes: Any, filename: str, config: dict[str, Any]) -> dict[str, Any]:
    safety = config.get("safety", {}) if isinstance(config.get("safety"), dict) else {}
    reject_3d = bool(safety.get("reject_3d_printer_gcode", True))
    allow_unknown = bool(safety.get("allow_unknown_gcode", True))
    scan_lines = int(safety.get("gcode_safety_scan_lines", 5000) or 5000)
    lines = _safe_text_lines(path_or_bytes, scan_lines)
    name = str(filename or "").lower()

    if not reject_3d:
        return {"ok": True, "reason": "3D-printer rejection disabled by config", "detected_type": "unknown", "matches": []}

    strong_markers = [
        ";flavor:marlin",
        "; generated by cura",
        ";generated with cura",
        "; generated by prusaslicer",
        "; generated by orcaslicer",
        "; generated by bambustudio",
        "; filament used",
        "; filament_type",
        "; nozzle_diameter",
        ";layer height",
        ";layer:",
        ";layer_count:",
        "start_print",
        "end_print",
        "set_print_stats_info",
        "m104",
        "m109",
        "m140",
        "m190",
        "m105",
        "m82",
        "m83",
        "g92 e",
        "m600",
        "m701",
        "m702",
        "m200",
    ]
    laser_markers = ["m3", "m4", "m5", "lasergrbl", "lightburn", "; bounds:"]

    strong_matches: list[str] = []
    laser_matches: list[str] = []
    extrusion_moves = 0
    g10g11_with_e = 0

    motion_with_e = re.compile(r"^\s*g0?1\b.*\be[-+]?\d", re.IGNORECASE)
    pure_e_move = re.compile(r"^\s*g0?1\b\s*e[-+]?\d", re.IGNORECASE)
    has_e_any = re.compile(r"\be[-+]?\d", re.IGNORECASE)

    for raw in lines:
        line = (raw or "").strip()
        low = line.lower()
        if not low:
            continue
        for marker in strong_markers:
            if marker in low:
                if marker not in strong_matches:
                    strong_matches.append(marker.upper() if marker.startswith("m") else marker)
        for marker in laser_markers:
            if marker in low:
                if marker not in laser_matches:
                    laser_matches.append(marker)
        if motion_with_e.search(low):
            extrusion_moves += 1
        elif pure_e_move.search(low):
            extrusion_moves += 1
        if (low.startswith("g10") or low.startswith("g11")) and has_e_any.search(low):
            g10g11_with_e += 1

    matches: list[str] = list(strong_matches)
    if extrusion_moves >= 3:
        matches.append("G1 E extrusion")
    if g10g11_with_e > 0:
        matches.append("G10/G11 with E")

    if strong_matches or extrusion_moves >= 3 or g10g11_with_e > 0:
        return {
            "ok": False,
            "reason": "Found 3D-printer slicer markers and/or extrusion commands.",
            "detected_type": "3d_printer",
            "matches": matches,
        }

    if laser_matches:
        return {"ok": True, "reason": "Laser markers detected.", "detected_type": "laser", "matches": laser_matches}

    if allow_unknown:
        return {
            "ok": True,
            "reason": "Unknown G-code profile allowed by config.",
            "detected_type": "unknown",
            "matches": [],
        }

    return {
        "ok": False,
        "reason": "Unknown G-code profile and allow_unknown_gcode is disabled.",
        "detected_type": "unknown",
        "matches": [],
    }

